ALTER TABLE "Character"
ADD COLUMN "energy" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN "maxEnergy" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN "energyUpdatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
