export interface ArtAssetRecord {
  id: string;
  path: string;
  kind: 'scene' | 'character' | 'enemy' | 'pet' | 'item' | 'ui' | 'vfx' | 'audio';
  license: 'original-generated-placeholder' | 'owned' | 'third-party-licensed';
  promptOrSource: string;
}

const GENERATED_LICENSE = 'original-generated-placeholder' as const;

function generatedSource(sourceFile: string): string {
  return `AI-generated original LOV2 asset. Source file: ${sourceFile}. Tool/source: Leonardo/Recraft/unknown. Needs final license review.`;
}

export const artManifest: ArtAssetRecord[] = [
  {
    id: 'scene-hub',
    path: '/assets/generated/scenes/scene-hub.jpg',
    kind: 'scene',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets/Backgrounds/background_001_Main_courtyard.jpg'),
  },
  {
    id: 'scene-tavern',
    path: '/assets/generated/scenes/scene-tavern.jpg',
    kind: 'scene',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets/Backgrounds/background_004_Tavern_shop_interior.jpg'),
  },
  {
    id: 'scene-map',
    path: '/assets/generated/scenes/scene-map.jpg',
    kind: 'scene',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets/Backgrounds/background_002_harbor_port_background.jpg'),
  },
  {
    id: 'scene-combat',
    path: '/assets/generated/scenes/scene-combat.jpg',
    kind: 'scene',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets/Backgrounds/background_003_Combat_arena_background.jpg'),
  },
  {
    id: 'scene-inventory',
    path: '/assets/generated/scenes/scene-inventory.jpg',
    kind: 'scene',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets/Backgrounds/background_005_Character_equipment_room.jpg'),
  },
  {
    id: 'scene-character',
    path: '/assets/generated/scenes/scene-character.jpg',
    kind: 'scene',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_missing/scenes/scene-character.jpg'),
  },
  {
    id: 'scene-pets',
    path: '/assets/generated/scenes/scene-pets.jpg',
    kind: 'scene',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_missing/scenes/scene-pets.jpg'),
  },
  {
    id: 'scene-journal',
    path: '/assets/generated/scenes/scene-journal.jpg',
    kind: 'scene',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_missing/scenes/scene-journal.jpg'),
  },
  {
    id: 'hero-nocturne',
    path: '/assets/generated/characters/hero-nocturne.png',
    kind: 'character',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_transparent/characters/hero-nocturne.png'),
  },
  {
    id: 'hero-nocturne-without-armor',
    path: '/assets/generated/characters/hero-nocturne-without-armor.png',
    kind: 'character',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_transparent/characters/hero-nocturne_without_armor.png'),
  },
  {
    id: 'hero-nocturne-without-armor-with-sword',
    path: '/assets/generated/characters/hero-nocturne-without-armor-with-sword.png',
    kind: 'character',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_transparent/characters/hero-nocturne_without_armor_with_sword.png'),
  },
  {
    id: 'hero-nocturne-without-sword',
    path: '/assets/generated/characters/hero-nocturne-without-sword.png',
    kind: 'character',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_transparent/characters/hero-nocturne_without_sword.png'),
  },
  {
    id: 'enemy-ash-baron',
    path: '/assets/generated/enemies/enemy-ash-baron.png',
    kind: 'enemy',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_transparent/enemies/enemy-ash-baron.png'),
  },
  {
    id: 'enemy-mist-bandit',
    path: '/assets/generated/enemies/enemy-mist-bandit.png',
    kind: 'enemy',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_transparent/enemies/enemy-mist-bandit.png'),
  },
  {
    id: 'enemy-harbor-wraith',
    path: '/assets/generated/enemies/enemy-harbor-wraith.png',
    kind: 'enemy',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_transparent/enemies/enemy-harbor-wraith.png'),
  },
  {
    id: 'enemy-rock-golem',
    path: '/assets/generated/enemies/enemy-rock-golem.png',
    kind: 'enemy',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_transparent/enemies/enemy-rock-golem.png'),
  },
  {
    id: 'enemy-travel-bone-shaman',
    path: '/assets/generated/enemies/travel/enemy_travel_bone_shaman.png',
    kind: 'enemy',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('apps/web/public/assets/generated/enemies/travel/enemy_travel_bone_shaman.png'),
  },
  {
    id: 'enemy-travel-cave-brute',
    path: '/assets/generated/enemies/travel/enemy_travel_cave_brute.png',
    kind: 'enemy',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('apps/web/public/assets/generated/enemies/travel/enemy_travel_cave_brute.png'),
  },
  {
    id: 'enemy-travel-corrupted-guardian',
    path: '/assets/generated/enemies/travel/enemy_travel_corrupted_guardian.png',
    kind: 'enemy',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('apps/web/public/assets/generated/enemies/travel/enemy_travel_corrupted_guardian.png'),
  },
  {
    id: 'enemy-travel-fog-harbor-wraith',
    path: '/assets/generated/enemies/travel/enemy_travel_fog_harbor_wraith.png',
    kind: 'enemy',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('apps/web/public/assets/generated/enemies/travel/enemy_travel_fog_harbor_wraith.png'),
  },
  {
    id: 'enemy-travel-frost-stalker',
    path: '/assets/generated/enemies/travel/enemy_travel_frost_stalker.png',
    kind: 'enemy',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('apps/web/public/assets/generated/enemies/travel/enemy_travel_frost_stalker.png'),
  },
  {
    id: 'enemy-travel-swamp-fang-beast',
    path: '/assets/generated/enemies/travel/enemy_travel_swamp_fang_beast.png',
    kind: 'enemy',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('apps/web/public/assets/generated/enemies/travel/enemy_travel_swamp_fang_beast.png'),
  },
  {
    id: 'enemy-arena-female-nocturne-mystic-01',
    path: '/assets/generated/enemies/arena/enemy_arena_female_nocturne_mystic_01.png',
    kind: 'enemy',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('apps/web/public/assets/generated/enemies/arena/enemy_arena_female_nocturne_mystic_01.png'),
  },
  {
    id: 'enemy-arena-female-oracle-ranger-01',
    path: '/assets/generated/enemies/arena/enemy_arena_female_oracle_ranger_01.png',
    kind: 'enemy',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('apps/web/public/assets/generated/enemies/arena/enemy_arena_female_oracle_ranger_01.png'),
  },
  {
    id: 'enemy-arena-female-veiled-swordsman-01',
    path: '/assets/generated/enemies/arena/enemy_arena_female_veiled_swordsman_01.png',
    kind: 'enemy',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('apps/web/public/assets/generated/enemies/arena/enemy_arena_female_veiled_swordsman_01.png'),
  },
  {
    id: 'enemy-arena-male-nocturne-swordsman-01',
    path: '/assets/generated/enemies/arena/enemy_arena_male_nocturne_swordsman_01 (1).png',
    kind: 'enemy',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('apps/web/public/assets/generated/enemies/arena/enemy_arena_male_nocturne_swordsman_01 (1).png'),
  },
  {
    id: 'enemy-arena-male-oracle-mystic-01',
    path: '/assets/generated/enemies/arena/enemy_arena_male_oracle_mystic_01.png',
    kind: 'enemy',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('apps/web/public/assets/generated/enemies/arena/enemy_arena_male_oracle_mystic_01.png'),
  },
  {
    id: 'enemy-arena-male-veiled-ranger-01',
    path: '/assets/generated/enemies/arena/enemy_arena_male_veiled_ranger_01.png',
    kind: 'enemy',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('apps/web/public/assets/generated/enemies/arena/enemy_arena_male_veiled_ranger_01.png'),
  },
  {
    id: 'pet-wyvern',
    path: '/assets/generated/pets/pet-wyvern.png',
    kind: 'pet',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_transparent/pets/pet-wyvern.png'),
  },
  {
    id: 'pet-dragon',
    path: '/assets/generated/pets/pet-dragon.png',
    kind: 'pet',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_transparent/pets/pet-dragon.png'),
  },
  {
    id: 'pet-cat',
    path: '/assets/generated/pets/pet-cat.png',
    kind: 'pet',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_transparent/pets/pet-cat.png'),
  },
  {
    id: 'pet-wolf',
    path: '/assets/generated/pets/pet-wolf.png',
    kind: 'pet',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_transparent/pets/pet-wolf.png'),
  },
  {
    id: 'icon-rapier',
    path: '/assets/generated/items/icon-rapier.png',
    kind: 'item',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_transparent/items/icon-rapier.png'),
  },
  {
    id: 'icon-starter-sword',
    path: '/assets/original/icon-starter-sword.svg',
    kind: 'item',
    license: GENERATED_LICENSE,
    promptOrSource: 'Original LOV2 vector placeholder drawn in-repo for the starter sword item.',
  },
  {
    id: 'icon-starter-bow',
    path: '/assets/original/icon-starter-bow.svg',
    kind: 'item',
    license: GENERATED_LICENSE,
    promptOrSource: 'Original LOV2 vector placeholder drawn in-repo for the starter bow item.',
  },
  {
    id: 'icon-starter-staff',
    path: '/assets/original/icon-starter-staff.svg',
    kind: 'item',
    license: GENERATED_LICENSE,
    promptOrSource: 'Original LOV2 vector placeholder drawn in-repo for the starter staff item.',
  },
  {
    id: 'icon-vest',
    path: '/assets/generated/items/icon-vest.png',
    kind: 'item',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_transparent/items/icon-vest.png'),
  },
  {
    id: 'icon-onyx',
    path: '/assets/generated/items/icon-onyx.png',
    kind: 'item',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_transparent/items/icon-onyx.png'),
  },
  {
    id: 'icon-wyvern',
    path: '/assets/generated/items/icon-wyvern.png',
    kind: 'item',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_transparent/items/icon-wyvern.png'),
  },
  {
    id: 'icon-moon-gem',
    path: '/assets/generated/items/icon-moon-gem.jpg',
    kind: 'item',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets/Equipment/Equipment_item_icon_009_Gem_premium_currency_icon.jpg'),
  },
  {
    id: 'icon-gold-coin',
    path: '/assets/generated/items/icon-gold-coin.jpg',
    kind: 'item',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets/Equipment/Equipment_item_icon_010_Gold_coin_icon.jpg'),
  },
  {
    id: 'ui-hotspot-hub-tavern',
    path: '/assets/generated/hotspots/hub/hotspot-tavern.png',
    kind: 'ui',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_hotspots/hub/hotspot-tavern.png'),
  },
  {
    id: 'ui-hotspot-hub-arena',
    path: '/assets/generated/hotspots/hub/hotspot-arena.png',
    kind: 'ui',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_hotspots/hub/hotspot-arena.png'),
  },
  {
    id: 'ui-hotspot-hub-store',
    path: '/assets/generated/hotspots/hub/hotspot-shop.png',
    kind: 'ui',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_hotspots/hub/hotspot-shop.png'),
  },
  {
    id: 'ui-hotspot-hub-sign',
    path: '/assets/generated/hotspots/hub/hotspot-harbor-sign.png',
    kind: 'ui',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_hotspots/hub/hotspot-harbor-sign.png'),
  },
  {
    id: 'ui-hotspot-hub-fountain',
    path: '/assets/generated/hotspots/hub/hotspot-fountain.png',
    kind: 'ui',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_hotspots/hub/hotspot-fountain.png'),
  },
  {
    id: 'ui-hotspot-map-town',
    path: '/assets/generated/hotspots/map/hotspot-town-return.png',
    kind: 'ui',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_hotspots/map/hotspot-town-return.png'),
  },
  {
    id: 'ui-hotspot-map-forge',
    path: '/assets/generated/hotspots/map/hotspot-forge.png',
    kind: 'ui',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_hotspots/map/hotspot-forge.png'),
  },
  {
    id: 'ui-hotspot-map-tower',
    path: '/assets/generated/hotspots/map/hotspot-boss-tower.png',
    kind: 'ui',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_hotspots/map/hotspot-boss-tower.png'),
  },
  {
    id: 'ui-hotspot-map-boatman',
    path: '/assets/generated/hotspots/map/hotspot-boatman.png',
    kind: 'ui',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_hotspots/map/hotspot-boatman.png'),
  },
  {
    id: 'ui-journal-panel-background',
    path: '/assets/generated/hotspots/journal/journal-panel-background.png',
    kind: 'ui',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets_hotspots/journal/journal-panel-background.png'),
  },
  {
    id: 'ui-appearance-face-card',
    path: '/assets/generated/ui/appearance/ui-appearance-face-card.jpg',
    kind: 'ui',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets/Appearance/Appearance_customization_001_Face_selection_card.jpg'),
  },
  {
    id: 'ui-appearance-hair-style',
    path: '/assets/generated/ui/appearance/ui-appearance-hair-style.jpg',
    kind: 'ui',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets/Appearance/Appearance_customization_002_Hair_style_thumbnail.jpg'),
  },
  {
    id: 'ui-appearance-hair-color',
    path: '/assets/generated/ui/appearance/ui-appearance-hair-color.jpg',
    kind: 'ui',
    license: GENERATED_LICENSE,
    promptOrSource: generatedSource('_incoming_assets/Appearance/Appearance_customization_003_Hair_color_thumbnail.jpg'),
  },
];
